package com.example.mobappprototype.utils

import com.example.mobappprototype.R
import com.example.mobappprototype.model.Review
import com.example.mobappprototype.model.ScheduleTutor
import com.example.mobappprototype.model.Tutor
import com.example.mobappprototype.model.Subject

object DummyData {
    val subjectList = listOf(
        Subject.GEN_MATH,
        Subject.PHYSICS,
        Subject.CHEMISTRY,
        Subject.BIOLOGY,
        Subject.COMPUTER_SCIENCE,
        Subject.LAW,
        Subject.ARCHITECTURE,
        Subject.BUSINESS,
        Subject.IT,
        Subject.ENGINEERING,
        Subject.MACHINE_LEARNING
    )

    val tutorList = listOf(
        Tutor("Michael Lee", R.drawable.guy1, listOf(Subject.ENGINEERING, Subject.COMPUTER_SCIENCE), 4.2f),
        Tutor("Alice Jones", R.drawable.girl2, listOf(Subject.LAW, Subject.BUSINESS), 4.7f),
        Tutor("David Williams", R.drawable.guy2, listOf(Subject.PHYSICS, Subject.GEN_MATH), 3.8f),
        Tutor("Emily Brown", R.drawable.girl1, listOf(Subject.CHEMISTRY, Subject.BIOLOGY), 4.9f),
        Tutor("Charles Davis", R.drawable.guy0, listOf(Subject.ARCHITECTURE, Subject.ENGINEERING), 4.3f),
        Tutor("Sarah Miller", R.drawable.girl3, listOf(Subject.IT, Subject.COMPUTER_SCIENCE), 4.1f),
        Tutor("William Clark", R.drawable.guy2, listOf(Subject.BUSINESS, Subject.LAW), 4.6f),
        Tutor("Jennifer Garcia", R.drawable.girl1, listOf(Subject.BIOLOGY, Subject.CHEMISTRY), 4.8f),
        Tutor("Richard Hernandez", R.drawable.guy1, listOf(Subject.GEN_MATH, Subject.PHYSICS), 3.9f),
        Tutor("Amanda Young", R.drawable.girl0, listOf(Subject.IT, Subject.MACHINE_LEARNING), 4.4f),
        Tutor("Daniel Johnson", R.drawable.guy0, listOf(Subject.ENGINEERING, Subject.ARCHITECTURE), 4.0f),
        Tutor("Elizabeth Moore", R.drawable.girl2, listOf(Subject.LAW, Subject.BUSINESS), 4.5f),
        Tutor("Christopher Taylor", R.drawable.guy1, listOf(Subject.PHYSICS, Subject.GEN_MATH), 3.7f),
        Tutor("Ashley Lewis", R.drawable.girl3, listOf(Subject.CHEMISTRY, Subject.BIOLOGY), 5.0f),
        Tutor("Matthew Garcia", R.drawable.guy2, listOf(Subject.ARCHITECTURE, Subject.ENGINEERING), 4.2f),
        Tutor("Nicole Baker", R.drawable.girl1, listOf(Subject.IT, Subject.COMPUTER_SCIENCE), 4.8f),
        Tutor("Joseph Robinson", R.drawable.guy1, listOf(Subject.BUSINESS, Subject.LAW), 3.5f),
        Tutor("Catherine Allen", R.drawable.girl3, listOf(Subject.BIOLOGY, Subject.CHEMISTRY), 4.9f),
        Tutor("Robert Thompson", R.drawable.guy2, listOf(Subject.GEN_MATH, Subject.PHYSICS), 4.1f),
        Tutor("Jessica Sanchez", R.drawable.girl2, listOf(Subject.IT, Subject.MACHINE_LEARNING), 4.6f),
        Tutor("Andrew Walker", R.drawable.guy1, listOf(Subject.ENGINEERING, Subject.ARCHITECTURE), 4.4f),
        Tutor("Margaret Wilson", R.drawable.girl0, listOf(Subject.LAW, Subject.BUSINESS), 4.7f),
        Tutor("Kevin Garcia", R.drawable.guy2, listOf(Subject.PHYSICS, Subject.GEN_MATH), 3.9f),
        Tutor("Kimberly Moore", R.drawable.girl1, listOf(Subject.CHEMISTRY, Subject.BIOLOGY), 4.5f),
        Tutor("Ronald Hernandez", R.drawable.guy1, listOf(Subject.ARCHITECTURE, Subject.ENGINEERING), 4.0f),
        Tutor("Sandra Young", R.drawable.girl3, listOf(Subject.IT, Subject.COMPUTER_SCIENCE), 4.2f),
        Tutor("Daniel Johnson", R.drawable.guy2, listOf(Subject.BUSINESS, Subject.LAW), 4.6f),
        Tutor("Elizabeth Moore", R.drawable.girl2, listOf(Subject.BIOLOGY, Subject.CHEMISTRY), 4.8f),
        Tutor("Christopher Taylor", R.drawable.guy1, listOf(Subject.GEN_MATH, Subject.PHYSICS), 4.3f),
        Tutor("Ashley Lewis", R.drawable.girl3, listOf(Subject.IT, Subject.MACHINE_LEARNING), 3.2f),
        Tutor("Michael Lee", R.drawable.guy1, listOf(Subject.ENGINEERING, Subject.COMPUTER_SCIENCE), 4.2f),
        Tutor("Alice Jones", R.drawable.girl2, listOf(Subject.LAW, Subject.BUSINESS), 4.7f),
        Tutor("David Williams", R.drawable.guy0, listOf(Subject.PHYSICS, Subject.GEN_MATH), 3.8f),
        Tutor("Emily Brown", R.drawable.girl1, listOf(Subject.CHEMISTRY, Subject.BIOLOGY), 4.9f),
        Tutor("Charles Davis", R.drawable.guy1, listOf(Subject.ARCHITECTURE, Subject.ENGINEERING), 4.3f),
        Tutor("Sarah Miller", R.drawable.girl3, listOf(Subject.IT, Subject.COMPUTER_SCIENCE), 4.1f),
        Tutor("William Clark", R.drawable.guy2, listOf(Subject.BUSINESS, Subject.LAW), 4.6f),
        Tutor("Jennifer Garcia", R.drawable.girl0, listOf(Subject.BIOLOGY, Subject.CHEMISTRY), 4.8f),
        Tutor("Richard Hernandez", R.drawable.guy1, listOf(Subject.GEN_MATH, Subject.PHYSICS), 3.9f),
        Tutor("Amanda Young", R.drawable.girl3, listOf(Subject.IT, Subject.MACHINE_LEARNING), 4.4f),
        Tutor("Daniel Johnson", R.drawable.guy2, listOf(Subject.ENGINEERING, Subject.ARCHITECTURE), 4.0f),
        Tutor("Elizabeth Moore", R.drawable.girl2, listOf(Subject.LAW, Subject.BUSINESS), 4.5f),
        Tutor("Christopher Taylor", R.drawable.guy1, listOf(Subject.PHYSICS, Subject.GEN_MATH), 3.7f),
        Tutor("Ashley Lewis", R.drawable.girl0, listOf(Subject.CHEMISTRY, Subject.BIOLOGY), 5.0f),
        Tutor("Matthew Garcia", R.drawable.guy2, listOf(Subject.ARCHITECTURE, Subject.ENGINEERING), 4.2f),
        Tutor("Nicole Baker", R.drawable.girl1, listOf(Subject.IT, Subject.COMPUTER_SCIENCE), 4.8f),
        Tutor("Joseph Robinson", R.drawable.guy1, listOf(Subject.BUSINESS, Subject.LAW), 3.5f),
        Tutor("Catherine Allen", R.drawable.girl3, listOf(Subject.BIOLOGY, Subject.CHEMISTRY), 4.9f),
        Tutor("Robert Thompson", R.drawable.guy2, listOf(Subject.GEN_MATH, Subject.PHYSICS), 4.1f),
        Tutor("Jessica Sanchez", R.drawable.girl2, listOf(Subject.IT, Subject.MACHINE_LEARNING), 4.6f),
        Tutor("Andrew Walker", R.drawable.guy1, listOf(Subject.ENGINEERING, Subject.ARCHITECTURE), 4.4f),
        Tutor("Margaret Wilson", R.drawable.girl0, listOf(Subject.LAW, Subject.BUSINESS), 4.7f),
        Tutor("Kevin Garcia", R.drawable.guy2, listOf(Subject.PHYSICS, Subject.GEN_MATH), 3.9f),
        Tutor("Kimberly Moore", R.drawable.girl1, listOf(Subject.CHEMISTRY, Subject.BIOLOGY), 4.5f),
        Tutor("Ronald Hernandez", R.drawable.guy1, listOf(Subject.ARCHITECTURE, Subject.ENGINEERING), 4.0f),
        Tutor("Sandra Young", R.drawable.girl3, listOf(Subject.IT, Subject.COMPUTER_SCIENCE), 4.2f),
        Tutor("Daniel Johnson", R.drawable.guy2, listOf(Subject.BUSINESS, Subject.LAW), 4.6f),
        Tutor("Elizabeth Moore", R.drawable.girl2, listOf(Subject.BIOLOGY, Subject.CHEMISTRY), 4.8f),
        Tutor("Christopher Taylor", R.drawable.guy1, listOf(Subject.GEN_MATH, Subject.PHYSICS), 4.3f),
        Tutor("Ashley Lewis", R.drawable.girl0, listOf(Subject.IT, Subject.MACHINE_LEARNING), 3.2f),
        Tutor("Ethan Davis", R.drawable.guy1, listOf(Subject.COMPUTER_SCIENCE, Subject.GEN_MATH), 4.7f),
        Tutor("Olivia Martinez", R.drawable.girl2, listOf(Subject.BUSINESS, Subject.LAW), 4.2f),
        Tutor("Noah Rodriguez", R.drawable.guy2, listOf(Subject.PHYSICS, Subject.CHEMISTRY), 3.8f),
        Tutor("Ava Perez", R.drawable.girl1, listOf(Subject.BIOLOGY, Subject.IT), 4.9f),
        Tutor("Jacob Hernandez", R.drawable.guy1, listOf(Subject.ENGINEERING, Subject.ARCHITECTURE), 4.3f),
        Tutor("Sophia Martinez", R.drawable.girl3, listOf(Subject.LAW, Subject.BUSINESS), 4.1f),
        Tutor("William Garcia", R.drawable.guy2, listOf(Subject.GEN_MATH, Subject.PHYSICS), 4.6f),
        Tutor("Emily Rodriguez", R.drawable.girl1, listOf(Subject.CHEMISTRY, Subject.BIOLOGY), 4.8f),
        Tutor("Charles Hernandez", R.drawable.guy0, listOf(Subject.IT, Subject.COMPUTER_SCIENCE), 3.9f),
        Tutor("Sarah Martinez", R.drawable.girl3, listOf(Subject.BUSINESS, Subject.LAW), 4.4f),
        Tutor("Daniel Garcia", R.drawable.guy2, listOf(Subject.ENGINEERING, Subject.ARCHITECTURE), 4.0f),
        Tutor("Elizabeth Rodriguez", R.drawable.girl2, listOf(Subject.LAW, Subject.BUSINESS), 4.5f),
        Tutor("Christopher Hernandez", R.drawable.guy1, listOf(Subject.PHYSICS, Subject.GEN_MATH), 3.7f),
        Tutor("Ashley Martinez", R.drawable.girl3, listOf(Subject.CHEMISTRY, Subject.BIOLOGY), 5.0f),
        Tutor("Matthew Garcia", R.drawable.guy2, listOf(Subject.ARCHITECTURE, Subject.ENGINEERING), 4.2f),
        Tutor("Nicole Rodriguez", R.drawable.girl1, listOf(Subject.IT, Subject.COMPUTER_SCIENCE), 4.8f),
        Tutor("Joseph Hernandez", R.drawable.guy0, listOf(Subject.BUSINESS, Subject.LAW), 3.5f),
        Tutor("Catherine Martinez", R.drawable.girl3, listOf(Subject.BIOLOGY, Subject.CHEMISTRY), 5.0f)
        )
}